#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	if ! getent group ftpcloudfs > /dev/null 2>&1 ; then
		addgroup --system ftpcloudfs >/dev/null
	fi
	if ! getent passwd ftpcloudfs > /dev/null 2>&1 ; then
		adduser --system --home /var/log/ftp-cloudfs --ingroup ftpcloudfs --no-create-home --shell /bin/false ftpcloudfs > /dev/null 2>&1
	fi

	# log directory
	mkdir -m 0700 -p /var/log/ftp-cloudfs
	touch /var/log/ftp-cloudfs/ftp-cloudfs.log
	chmod 0640 /var/log/ftp-cloudfs/ftp-cloudfs.log
	chown -R ftpcloudfs:ftpcloudfs /var/log/ftp-cloudfs

	# pid file directory
	mkdir -m 0700 -p /var/run/ftp-cloudfs
	chown -R ftpcloudfs:ftpcloudfs /var/run/ftp-cloudfs

	if [ ! -e /etc/ftpcloudfs.conf ] ; then
		install -D -m 0640 -g ftpcloudfs -o ftpcloudfs /usr/share/ftpcloudfs/ftpcloudfs.conf /etc/ftpcloudfs.conf
		GID=`id -g ftpcloudfs`
		UID=`id -u ftpcloudfs`
		sed -i -e 's|^[ \t]*uid[ \t]*=.*|uid = '${UID}'|' /etc/ftpcloudfs.conf
		sed -i -e 's|^[ \t]*gid[ \t]*=.*|gid = '${GID}'|' /etc/ftpcloudfs.conf
	fi
fi

#DEBHELPER#

exit 0
