#!/bin/sh

if [ "$1" = "configure" ];then
    chown daemon: /var/log/ftp-cloudfs
    chmod 0755 /var/log/ftp-cloudfs
fi

# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -a
fi
# End automatically added section

set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ftp-cloudfs" ]; then
	update-rc.d ftp-cloudfs defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d ftp-cloudfs start || exit $?
	else
		/etc/init.d/ftp-cloudfs start || exit $?
	fi
fi
# End automatically added section
