#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	echo "Purging ftpcloudfs."
	[ -e /etc/ftpcloudfs.conf ] && rm -f /etc/ftpcloudfs.conf
	[ -e /var/run/ftp-cloudfs ] && rm -fr /var/run/ftp-cloudfs
	[ -e /var/log/ftp-cloudfs ] && rm -fr /var/log/ftp-cloudfs
	[ -e /etc/logrotate.d/ftpcloudfs ] && rm -f /etc/logrotate.d/ftpcloudfs
fi

#DEBHELPER#

exit 0
